-- §32: ランキング仕込み — 地域＋opt-in列追加
ALTER TABLE ky_tenants ADD COLUMN IF NOT EXISTS prefecture TEXT NOT NULL DEFAULT '';
ALTER TABLE ky_tenants ADD COLUMN IF NOT EXISTS area TEXT NOT NULL DEFAULT '';
ALTER TABLE ky_tenants ADD COLUMN IF NOT EXISTS ranking_opt_in BOOLEAN NOT NULL DEFAULT FALSE;
